In [1]:
from keras.models import model_from_json
from keras.optimizers import SGD

json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
model = model_from_json(loaded_model_json)
# load weights into new model
model.load_weights("model.h5")
#loaded_model.load_weights("Binary_Code_model_weights.hdf5")
print("Loaded model from disk")


# Evaluate loaded model on test data
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Loaded model from disk


In [5]:
#Testing accuracy on testing data
import numpy as np
import pandas as pd
from keras.preprocessing import image
from tqdm import tqdm
from sklearn.metrics import confusion_matrix,accuracy_score
classes = np.array(['Normal','Benign','Malignant'])
test_file = pd.read_csv('test.csv')
y_true=test_file['Label']
test_image = []
prediction=[]
for i in tqdm(range(test_file.shape[0])):
    imge = image.load_img('Dataset/PDDSM/Data/'+test_file['File Name'][i],target_size=(128,128,3))
    img = image.img_to_array(imge)
    img = img/255
    proba = model.predict(img.reshape(1,128,128,3))
    top = np.argsort(proba[0])[-1]
    prediction.append(classes[top])
con=confusion_matrix(y_true,prediction)
print(con)

100%|██████████████████████████████████████████████████████████████████████████████| 1016/1016 [00:59<00:00, 19.06it/s]


[[  2   0 332]
 [  1   2 346]
 [  0   0 333]]
